version: '2'

services:
  baseimg:
    build:
      context: .
      dockerfile: Dockerfile
    image: lanparty-packages:base
  kernelimg:
    build:
      context: .
      dockerfile: Dockerfile-kernel
    image: lanparty-packages:kernel
  joki:
    image: lanparty-packages:base
    working_dir: /build/recipes/joki
    environment:
      - "GOPATH=/build/recipes/joki"
      - "GOBIN=${GOPATH}/bin"
    command: bash -c "apt-get update && fpm-cook clean && fpm-cook --pkg-dir /pkg"
    volumes:
      - .:/build
      - ./pkg:/pkg
  consul:
    image: lanparty-packages:base
    working_dir: /build/recipes/consul
    command: bash -c "apt-get update && fpm-cook clean && fpm-cook --pkg-dir /pkg"
    volumes:
      - .:/build
      - ./pkg:/pkg
  nginx:
    image: lanparty-packages:base
    working_dir: /build/recipes/nginx
    command: bash -c "apt-get update && fpm-cook clean && fpm-cook --pkg-dir /pkg"
    volumes:
      - .:/build
      - ./pkg:/pkg
  nginx-git:
    image: lanparty-packages:base
    working_dir: /build/recipes/nginx
    command: bash -c "apt-get update && fpm-cook clean && fpm-cook --pkg-dir /pkg package nginx-git.rb"
    volumes:
      - .:/build
      - ./pkg:/pkg
  php:
    image: lanparty-packages:base
    working_dir: /build/recipes/php5
    environment:
      - PKGDIR=/pkg
    command: bash -c "apt-get update && rake"
    volumes:
      - .:/build
      - ./pkg:/pkg
  kernel-ck-tick:
    image: lanparty-packages:kernel
    working_dir: /build/recipes/kernel-ck
    command: bash -c "apt-get update && fpm-cook clean tick.rb && fpm-cook --pkg-dir /pkg --skip-package package tick.rb"
    volumes:
      - .:/build
      - ./pkg:/pkg
  kernel-ck-notick:
    image: lanparty-packages:kernel
    working_dir: /build/recipes/kernel-ck
    command: bash -c "apt-get update && fpm-cook clean notick.rb && fpm-cook --pkg-dir /pkg --skip-package package notick.rb"
    volumes:
      - .:/build
      - ./pkg:/pkg
